# Fichier services.yaml
parameters:
    # Définir ici les paramètres de ton application (si nécessaire)
    # Exemple: app.some_parameter: 'value'

services:
    # Configuration par défaut des services
    _defaults:
        autowire: true      # Injection automatique des dépendances dans les services
        autoconfigure: true # Enregistrement automatique des services comme commandes, abonnés aux événements, etc.

    # Services dans le répertoire src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajout des services pour les contrôleurs
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
